// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package usecase

import (
	"context"
	"sync"
	"time"
)

// Ensure, that ExampleRepositoryMock does implement ExampleRepository.
// If this is not the case, regenerate this file with moq.
var _ ExampleRepository = &ExampleRepositoryMock{}

// ExampleRepositoryMock is a mock implementation of ExampleRepository.
//
//	func TestSomethingThatUsesExampleRepository(t *testing.T) {
//
//		// make and configure a mocked ExampleRepository
//		mockedExampleRepository := &ExampleRepositoryMock{
//			CountCreatedSinceFunc: func(ctx context.Context, t time.Time) (int64, error) {
//				panic("mock out the CountCreatedSince method")
//			},
//			CreateFunc: func(ctx context.Context, entity *ExampleEntity) error {
//				panic("mock out the Create method")
//			},
//			FindByEmailFunc: func(ctx context.Context, email string) (*ExampleEntity, error) {
//				panic("mock out the FindByEmail method")
//			},
//			LockByEmailFunc: func(ctx context.Context, email string) error {
//				panic("mock out the LockByEmail method")
//			},
//			WithinTxFunc: func(ctx context.Context, fn func(ctx context.Context) error) error {
//				panic("mock out the WithinTx method")
//			},
//		}
//
//		// use mockedExampleRepository in code that requires ExampleRepository
//		// and then make assertions.
//
//	}
type ExampleRepositoryMock struct {
	// CountCreatedSinceFunc mocks the CountCreatedSince method.
	CountCreatedSinceFunc func(ctx context.Context, t time.Time) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, entity *ExampleEntity) error

	// FindByEmailFunc mocks the FindByEmail method.
	FindByEmailFunc func(ctx context.Context, email string) (*ExampleEntity, error)

	// LockByEmailFunc mocks the LockByEmail method.
	LockByEmailFunc func(ctx context.Context, email string) error

	// WithinTxFunc mocks the WithinTx method.
	WithinTxFunc func(ctx context.Context, fn func(ctx context.Context) error) error

	// calls tracks calls to the methods.
	calls struct {
		// CountCreatedSince holds details about calls to the CountCreatedSince method.
		CountCreatedSince []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// T is the t argument value.
			T time.Time
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entity is the entity argument value.
			Entity *ExampleEntity
		}
		// FindByEmail holds details about calls to the FindByEmail method.
		FindByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// LockByEmail holds details about calls to the LockByEmail method.
		LockByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// WithinTx holds details about calls to the WithinTx method.
		WithinTx []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(ctx context.Context) error
		}
	}
	lockCountCreatedSince sync.RWMutex
	lockCreate            sync.RWMutex
	lockFindByEmail       sync.RWMutex
	lockLockByEmail       sync.RWMutex
	lockWithinTx          sync.RWMutex
}

// CountCreatedSince calls CountCreatedSinceFunc.
func (mock *ExampleRepositoryMock) CountCreatedSince(ctx context.Context, t time.Time) (int64, error) {
	if mock.CountCreatedSinceFunc == nil {
		panic("ExampleRepositoryMock.CountCreatedSinceFunc: method is nil but ExampleRepository.CountCreatedSince was just called")
	}
	callInfo := struct {
		Ctx context.Context
		T   time.Time
	}{
		Ctx: ctx,
		T:   t,
	}
	mock.lockCountCreatedSince.Lock()
	mock.calls.CountCreatedSince = append(mock.calls.CountCreatedSince, callInfo)
	mock.lockCountCreatedSince.Unlock()
	return mock.CountCreatedSinceFunc(ctx, t)
}

// CountCreatedSinceCalls gets all the calls that were made to CountCreatedSince.
// Check the length with:
//
//	len(mockedExampleRepository.CountCreatedSinceCalls())
func (mock *ExampleRepositoryMock) CountCreatedSinceCalls() []struct {
	Ctx context.Context
	T   time.Time
} {
	var calls []struct {
		Ctx context.Context
		T   time.Time
	}
	mock.lockCountCreatedSince.RLock()
	calls = mock.calls.CountCreatedSince
	mock.lockCountCreatedSince.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *ExampleRepositoryMock) Create(ctx context.Context, entity *ExampleEntity) error {
	if mock.CreateFunc == nil {
		panic("ExampleRepositoryMock.CreateFunc: method is nil but ExampleRepository.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Entity *ExampleEntity
	}{
		Ctx:    ctx,
		Entity: entity,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, entity)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedExampleRepository.CreateCalls())
func (mock *ExampleRepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	Entity *ExampleEntity
} {
	var calls []struct {
		Ctx    context.Context
		Entity *ExampleEntity
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// FindByEmail calls FindByEmailFunc.
func (mock *ExampleRepositoryMock) FindByEmail(ctx context.Context, email string) (*ExampleEntity, error) {
	if mock.FindByEmailFunc == nil {
		panic("ExampleRepositoryMock.FindByEmailFunc: method is nil but ExampleRepository.FindByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockFindByEmail.Lock()
	mock.calls.FindByEmail = append(mock.calls.FindByEmail, callInfo)
	mock.lockFindByEmail.Unlock()
	return mock.FindByEmailFunc(ctx, email)
}

// FindByEmailCalls gets all the calls that were made to FindByEmail.
// Check the length with:
//
//	len(mockedExampleRepository.FindByEmailCalls())
func (mock *ExampleRepositoryMock) FindByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockFindByEmail.RLock()
	calls = mock.calls.FindByEmail
	mock.lockFindByEmail.RUnlock()
	return calls
}

// LockByEmail calls LockByEmailFunc.
func (mock *ExampleRepositoryMock) LockByEmail(ctx context.Context, email string) error {
	if mock.LockByEmailFunc == nil {
		panic("ExampleRepositoryMock.LockByEmailFunc: method is nil but ExampleRepository.LockByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockLockByEmail.Lock()
	mock.calls.LockByEmail = append(mock.calls.LockByEmail, callInfo)
	mock.lockLockByEmail.Unlock()
	return mock.LockByEmailFunc(ctx, email)
}

// LockByEmailCalls gets all the calls that were made to LockByEmail.
// Check the length with:
//
//	len(mockedExampleRepository.LockByEmailCalls())
func (mock *ExampleRepositoryMock) LockByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockLockByEmail.RLock()
	calls = mock.calls.LockByEmail
	mock.lockLockByEmail.RUnlock()
	return calls
}

// WithinTx calls WithinTxFunc.
func (mock *ExampleRepositoryMock) WithinTx(ctx context.Context, fn func(ctx context.Context) error) error {
	if mock.WithinTxFunc == nil {
		panic("ExampleRepositoryMock.WithinTxFunc: method is nil but ExampleRepository.WithinTx was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(ctx context.Context) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockWithinTx.Lock()
	mock.calls.WithinTx = append(mock.calls.WithinTx, callInfo)
	mock.lockWithinTx.Unlock()
	return mock.WithinTxFunc(ctx, fn)
}

// WithinTxCalls gets all the calls that were made to WithinTx.
// Check the length with:
//
//	len(mockedExampleRepository.WithinTxCalls())
func (mock *ExampleRepositoryMock) WithinTxCalls() []struct {
	Ctx context.Context
	Fn  func(ctx context.Context) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(ctx context.Context) error
	}
	mock.lockWithinTx.RLock()
	calls = mock.calls.WithinTx
	mock.lockWithinTx.RUnlock()
	return calls
}
